void updateAPDisplay(void);
void updateLastDetected(void);
void updateAOETorDisplay(void);
void updateHealthDisplay(void);
void updateLocationDisplay(void);
void printToMain(const int x, const int y, const char *const str);
void printToTxtScr(const int x, const int y, const char *const str);
void printToOptWin(const int x, const int y, const char *const str);
void printPieces(void);
void printPlayerSub(void);
void printOptWin(void);
void displayAOE(const int limit);
void displaySonar(void);
void printNumSign(const int i,const int j, const int x, const int y, const int color);
void printLastDetected(SHIP *const ship);
void animateTorpedo(const int limit);